### PR TITLE
fix type mapping

### LINKED ISSUE #26: Use of double produces an undefined type error
Looks like the use of `double` in a proto message produces an error. Example message:

```
message GetLocalInfoRequest {
  double lat = 1;
  double lon = 2;
}
```

Compilation result:

```
undefined type: {
  name: 'lat',
  number: 1,
  label: 1,
  type: 1,
  typeName: undefined,
  extendee: undefined,
  defaultValue: undefined,
  oneofIndex: undefined,
  jsonName: 'lat',
  options: undefined,
  proto3Optional: undefined
} proto.raceday.v3.GetLocalInfoRequest
undefined type: {
  name: 'lon',
  number: 2,
  label: 1,
  type: 1,
  typeName: undefined,
  extendee: undefined,
  defaultValue: undefined,
  oneofIndex: undefined,
  jsonName: 'lon',
  options: undefined,
  proto3Optional: undefined
} proto.raceday.v3.GetLocalInfoRequest
```

### PR DESCRIPTION
**Pull request by peuter**
closes #26

### CODE REVIEW

**Comment by sknick** [comment]
Getting this error when I try to compile my app:

```
Error: Cannot find module 'memory-fs'
Require stack:
- /home/developer/Source/github.com/raceday-watch/raceday/Client/API/Qooxdoo/node_modules/protoc-gen-qx/index.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:995:15)
    at Function.Module._load (node:internal/modules/cjs/loader:841:27)
    at Module.require (node:internal/modules/cjs/loader:1067:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/home/developer/Source/github.com/raceday-watch/raceday/Client/API/Qooxdoo/node_modules/protoc-gen-qx/index.js:5:26)
    at Module._compile (node:internal/modules/cjs/loader:1165:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1219:10)
    at Module.load (node:internal/modules/cjs/loader:1043:32)
    at Function.Module._load (node:internal/modules/cjs/loader:878:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/developer/Source/github.com/raceday-watch/raceday/Client/API/Qooxdoo/node_modules/protoc-gen-qx/index.js'
  ]
}
--qx_out: protoc-gen-qx: Plugin failed with status code 1.
make: *** [Makefile:21: proto-gen-js] Error 1
```

**Comment by peuter** [comment]
This is weird, seems as if that dependecy was never defined in the package.json. I wonder how that ever worked on your side. Anways the original memory-js project has been deprecated and suggest to use memfs instead.
I changed that and also added the dependency to the package.json.

I also found some changes in an old repo of this project that I also merged. So lets hope everything is still working.

**Comment by sknick** [comment]
Still getting this:

```
developer@tuf:~/Source/github.com/raceday-watch/raceday$ make
rm -f Client/API/Qooxdoo/source/class/proto/raceday/v1/*
# Generate the JavaScript code from the gRPC API
cd Client/API/Qooxdoo && protoc -I ../../../API:../../../Third_Party/Protobufs \
        --plugin=protoc-gen-qx=./node_modules/.bin/protoc-gen-qx \
        --qx_out=. \
        model.proto grpc.proto
node:internal/modules/cjs/loader:998
  throw err;
  ^

Error: Cannot find module 'memory-fs'
Require stack:
- /home/developer/Source/github.com/raceday-watch/raceday/Client/API/Qooxdoo/node_modules/protoc-gen-qx/index.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:995:15)
    at Function.Module._load (node:internal/modules/cjs/loader:841:27)
    at Module.require (node:internal/modules/cjs/loader:1067:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/home/developer/Source/github.com/raceday-watch/raceday/Client/API/Qooxdoo/node_modules/protoc-gen-qx/index.js:5:26)
    at Module._compile (node:internal/modules/cjs/loader:1165:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1219:10)
    at Module.load (node:internal/modules/cjs/loader:1043:32)
    at Function.Module._load (node:internal/modules/cjs/loader:878:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/developer/Source/github.com/raceday-watch/raceday/Client/API/Qooxdoo/node_modules/protoc-gen-qx/index.js'
  ]
}
--qx_out: protoc-gen-qx: Plugin failed with status code 1.
make: *** [Makefile:21: proto-gen-js] Error 1
```

**Comment by peuter** [comment]
Then you either did not use the latest version or did not run an `npm install` after pulling the latest changes from this branch.

**Comment by sknick** [comment]
Ya, I figured something must be up. I had installed the version from this PR in one place but not another. I've fixed that but now am getting this webpack error:

```
# Generate the JavaScript code from the gRPC API
cd Client/API/Qooxdoo && protoc -I ../../../API:../../../Third_Party/Protobufs \
        --plugin=protoc-gen-qx=./node_modules/.bin/protoc-gen-qx \
        --qx_out=. \
        model.proto grpc.proto
/home/developer/Source/github.com/raceday-watch/raceday/Client/API/Qooxdoo/node_modules/webpack-sources/lib/SizeOnlySource.js:26
                throw this._error();
                ^

Error: Content and Map of this Source is not available (only size() is supported)
    at SizeOnlySource._error (/home/developer/Source/github.com/raceday-watch/raceday/Client/API/Qooxdoo/node_modules/webpack-sources/lib/SizeOnlySource.js:16:10)
    at SizeOnlySource.source (/home/developer/Source/github.com/raceday-watch/raceday/Client/API/Qooxdoo/node_modules/webpack-sources/lib/SizeOnlySource.js:26:14)
    at /home/developer/Source/github.com/raceday-watch/raceday/Client/API/Qooxdoo/node_modules/protoc-gen-qx/index.js:232:75
    at finalCallback (/home/developer/Source/github.com/raceday-watch/raceday/Client/API/Qooxdoo/node_modules/webpack/lib/Compiler.js:441:32)
    at /home/developer/Source/github.com/raceday-watch/raceday/Client/API/Qooxdoo/node_modules/webpack/lib/Compiler.js:505:17
    at /home/developer/Source/github.com/raceday-watch/raceday/Client/API/Qooxdoo/node_modules/webpack/lib/HookWebpackError.js:68:3
    at Hook.eval [as callAsync] (eval at create (/home/developer/Source/github.com/raceday-watch/raceday/Client/API/Qooxdoo/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/home/developer/Source/github.com/raceday-watch/raceday/Client/API/Qooxdoo/node_modules/tapable/lib/Hook.js:18:14)
    at Cache.storeBuildDependencies (/home/developer/Source/github.com/raceday-watch/raceday/Client/API/Qooxdoo/node_modules/webpack/lib/Cache.js:122:37)
    at /home/developer/Source/github.com/raceday-watch/raceday/Client/API/Qooxdoo/node_modules/webpack/lib/Compiler.js:501:19
--qx_out: protoc-gen-qx: Plugin failed with status code 1.
make: *** [Makefile:21: proto-gen-js] Error 1
```

**Comment by peuter** [comment]
Ok I downgraded webpack again to version 4 because I wasn't able to make it work with version 5.

**Comment by sknick** [comment]
Looks good! Merge it!

**Pull request merged**
